Repository HaRu-Developers/haru-web, pull requests merged in 2025-06, with the labels that each got.

#7 [Chore] 컬러, 폰트 시스템 설정
  .gitignore
  .vscode/settings.json
  .vscode/tailwind.json
  public/fonts/pretendard/LICENSE.txt
  public/fonts/pretendard/PretendardVariable.woff2
  src/app/[test]/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/styles/globals.css
  src/styles/token/colors.css
  src/styles/token/fonts.css
Labels: D-0

#18 [Chore] GitHooks + Prettier 설정
  .prettierignore
  commitlint.config.cjs
  eslint.config.mjs
  lefthook.yml
  package.json
  pnpm-lock.yaml
  prettier.config.cjs
  scripts/pre-rebase-check.cjs
  scripts/prepare-commit-msg.cjs
  scripts/run-commitlint.cjs
Labels: :broom: Chore, D-0

#13 [Test] CICD 적용 테스트
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  .github/workflows/storybook.yml
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  build.sh
  src/app/layout.tsx
  src/app/page.tsx
  src/common/components/Test.stories.tsx
  src/common/components/Test.tsx
  src/stories/Button.stories.ts
Labels: :pencil2: Test, D-0

#23 [Chore] prettier import order 변경
  .vscode/settings.json
  prettier.config.cjs
  src/app/layout.tsx
  tsconfig.json
Labels: D-0
