Repository HaRu-Developers/haru-web, pull requests merged in 2025-08, with the labels that each got.

#228 [Feat] 검색 API 연결 & 각 기능에 검색 모달 병렬 라우팅
  src/api/workspace/api-end-point.constants.ts
  src/api/workspace/api.types.ts
  src/api/workspace/get/apis/search-documents.ts
  src/api/workspace/get/queries/useSearchDocumentQuery.ts
  src/app/workspace/[workspaceId]/(assistant)/ai-meeting-manager/(modal-fallback)/search/page.tsx
  src/app/workspace/[workspaceId]/(assistant)/ai-meeting-manager/@modal/(.)search/page.tsx
  src/app/workspace/[workspaceId]/(assistant)/ai-meeting-manager/@modal/default.tsx
  src/app/workspace/[workspaceId]/(assistant)/ai-meeting-manager/layout.tsx
  src/app/workspace/[workspaceId]/(assistant)/sns-event-assistant/(modal-fallback)/search/page.tsx
  src/app/workspace/[workspaceId]/(assistant)/sns-event-assistant/@modal/(.)search/page.tsx
  src/app/workspace/[workspaceId]/(assistant)/sns-event-assistant/@modal/default.tsx
  src/app/workspace/[workspaceId]/(assistant)/sns-event-assistant/layout.tsx
  src/app/workspace/[workspaceId]/(assistant)/team-mood-tracker/(modal-fallback)/search/page.tsx
  src/app/workspace/[workspaceId]/(assistant)/team-mood-tracker/@modal/(.)search/page.tsx
  src/app/workspace/[workspaceId]/(assistant)/team-mood-tracker/@modal/default.tsx
  src/app/workspace/[workspaceId]/(assistant)/team-mood-tracker/layout.tsx
  src/app/workspace/[workspaceId]/(main)/(modal-fallback)/search/page.tsx
  src/app/workspace/[workspaceId]/(main)/@modal/(.)search/page.tsx
  src/app/workspace/[workspaceId]/(main)/layout.tsx
  src/app/workspace/[workspaceId]/(main)/page.tsx
  src/common/components/cta/ImageCta/ImageCta.client.tsx
  src/common/components/gnbs/GnbTop/GnbTop.client.tsx
  src/common/components/icons/IndividualIcons/IndividualIcons.tsx
  src/common/components/icons/IndividualIcons/IndividualIcons.types.ts
  src/common/components/inputs/InputSearchBox/InputSearchBox.client.tsx
  src/common/components/inputs/InputSearchBox/InputSearchBox.types.ts
  src/common/components/modals/SearchModal/RecentSearchChip/RecentSearchChip.client.tsx
  src/common/components/modals/SearchModal/RecentSearchChip/RecentSearchChip.types.ts
  src/common/components/modals/SearchModal/SearchModal.client.tsx
  src/common/components/modals/SearchModal/SearchModal.types.ts
  src/common/components/modals/SearchModal/SearchResultCard/SearchResultCard.client.tsx
  src/common/components/modals/SearchModal/SearchResultCard/SearchResultCard.types.ts
  src/common/components/modals/SearchModal/search-modal-mock-data.ts
  src/common/constants/query-key.constants.ts
  src/common/hooks/useDebounce.ts
  src/common/types/file-type.enum.ts
  src/features/on-boarding/mocks/dummy-files.ts
Labels: :recycle: Refactor, :sparkles: Feature, D-0

#254 [Refactor] landing 이동 및 workspace 버튼 수정
  src/app/landing/(landing-modal-fallback)/terms/page.tsx
  src/app/landing/page.tsx
  src/app/page.tsx
  src/app/workspace/[workspaceId]/sns-event-assistant/[snsEventId]/page.tsx
  src/common/components/WithoutWorkspaceSection/CreateWorkspaceButtonWrapper.client.tsx
  src/features/landing/components/LandingFull/LandingFull.client.tsx
  src/features/landing/components/landing-feature/LandingFeature/LandingFeature.client.tsx
  src/features/landing/components/landing-feature/LandingFeature/LandingFeature.types.ts
  src/features/sns-event-assistant/components/SnsLinkItem/SnsLinkItem.client.tsx
  src/features/sns-event-assistant/components/SnsLinkItem/SnsLinkItem.type.ts
  src/features/sns-event-assistant/components/SnsListButton/SnsListButton.client.tsx
  src/features/sns-event-assistant/components/SnsListButton/SnsListButton.types.ts
Labels: :recycle: Refactor, D-0

#279 [Feat] download Modal 병렬 라우팅 수정
  src/api/team-mood-tracker/end-point.constants.ts
  src/app/workspace/[workspaceId]/team-mood-tracker/@teamMoodTrackerGeneralModal/(.)survey/(.)[moodTrackerHashedId]/download/page.tsx
  src/app/workspace/[workspaceId]/team-mood-tracker/@teamMoodTrackerGeneralModal/(.)survey/[moodTrackerHashedId]/download/page.tsx
  src/app/workspace/[workspaceId]/team-mood-tracker/[moodTrackerHashedId]/@modal/default.tsx
  src/app/workspace/[workspaceId]/team-mood-tracker/[moodTrackerHashedId]/layout.tsx
  src/app/workspace/[workspaceId]/team-mood-tracker/[moodTrackerHashedId]/page.tsx
  src/app/workspace/[workspaceId]/team-mood-tracker/survey/[moodTrackerHashedId]/download/page.tsx
Labels: D-0

#280 [Fix] Create 오류 해결
  src/api/sns-event-assistant/api.types.ts
  src/api/sns-event-assistant/post/apis/create-sns-event.ts
  src/api/sns-event-assistant/post/mutations/useCreateSnsEventMutation.ts
  src/app/workspace/[workspaceId]/sns-event-assistant/@snsEventAssistantGeneralModal/(.)new-event/page.tsx
  src/features/sns-event-assistant/components/modal-client/CreatingEventModalClient/CreatingEventModalClient.tsx
  src/features/sns-event-assistant/components/modal-client/NewEventModalClient/NewEventModalClient.tsx
Labels: :wrench: Fix

#321 [Feat] 초대 리다이렉트 로직 및 API
  src/api/user/hooks/mutations/useLogin.ts
  src/app/auth/login/page.tsx
  src/app/auth/register/page.tsx
  src/features/auth/components/login-page/LoginForm/LoginForm.client.tsx
  src/features/auth/components/register-page/RegisterForm/RegisterForm.client.tsx
Labels: :sparkles: Feature

#319 [Refactor] button & Icon px - pxr 변경
  src/common/components/buttons/30px/AddWorkspaceButton/AddWorkspaceButton.client.tsx
  src/common/components/buttons/30px/DownloadButton/DownloadButton.client.tsx
  src/common/components/buttons/30px/EditCompleteButton/EditCompleteButton.client.tsx
  src/common/components/buttons/30px/NextStepButton/NextStepButton.client.tsx
  src/common/components/buttons/30px/SocialConnectButton/SocialConnectButton.client.tsx
  src/common/components/buttons/30px/WriteCompleteButton/WriteCompleteButton.client.tsx
  src/common/components/buttons/32px/ArrowButton/ArrowButton.client.tsx
  src/common/components/buttons/32px/CompleteSelectButton/CompleteSelectButton.client.tsx
  src/common/components/buttons/32px/InviteButton/InviteButton.client.tsx
  src/common/components/buttons/38px/AccountConnectButton/AccountConnectButton.client.tsx
  src/common/components/buttons/38px/ConfirmEndingRecordButton/ConfirmEndingRecordButton.client.tsx
  src/common/components/buttons/38px/DeleteButton/DeleteButton.client.tsx
  src/common/components/buttons/38px/MoveButton/MoveButton.client.tsx
  src/common/components/buttons/38px/SaveButton/SaveButton.client.tsx
  src/common/components/buttons/38px/SendLinkToTeamByEmailButton/SendLinkToTeamByEmailButton.client.tsx
  src/common/components/buttons/48px/ConnectInstagramAccountButton/ConnectInstagramAccountButton.client.tsx
  src/common/components/buttons/48px/LoginButton/LoginButton.client.tsx
  src/common/components/buttons/48px/RegisterButton/RegisterButton.client.tsx
  src/common/components/buttons/56px/AddQuestionButton/AddQuestionButton.client.tsx
  src/common/components/buttons/diverse-size/CancelButton/CancelButton.client.tsx
  src/common/components/buttons/diverse-size/SkipForNowButton/SkipForNowButton.client.tsx
  src/common/components/icons/AiQuestionIcons/AiQuestionIcons.tsx
  src/common/components/icons/CheckboxIcons/CheckboxIcons.tsx
  src/common/components/icons/CrossIcons/CrossIcons.tsx
  src/common/components/icons/Cta/CtaIcons.tsx
  src/common/components/icons/DownloadIcons/DownloadIcons.tsx
  src/common/components/icons/EyeIcons/EyeIcons.tsx
  src/common/components/icons/FeatureTabIcons/FeatureTabIcons.tsx
  src/common/components/icons/IndicatorIcons/IndicatorIcons.tsx
  src/common/components/icons/IndividualIcons/IndividualIcons.tsx
  src/common/components/icons/LeftGnbIcons/LeftGnbIcons.tsx
  src/common/components/icons/PlusIcons/PlusIcons.tsx
  src/common/components/icons/ProfileDropdownIcons/ProfileDropdownIcons.tsx
  src/common/components/icons/SpeakerIcons/SpeakerIcons.tsx
  src/styles/token/define-pxr.css
Labels: :recycle: Refactor

#316 [Refactor] 랜딩 애니메이션 수정
  src/features/landing/components/TitleSection/TitleSection.client.tsx
  src/features/landing/components/TitleSection/TitleSection.type.ts
  src/features/landing/components/landing-banner/TitleDisplay/TitleDisplay.client.tsx
  src/features/landing/components/landing-feature/LandingFeature/LandingFeature.client.tsx
  src/features/landing/components/landing-introduction/LandingIntroductuion/LandingIntroduction.client.tsx
  src/features/landing/components/landing-necessity/LandingNecessity/LandingNecessity.client.tsx
  src/features/landing/components/landing-necessity/SectionLayout/SectionLayout.client.tsx
  src/features/landing/components/landing-team/LandingTeam/LandingTeam.client.tsx
Labels: :recycle: Refactor

#346 [Fix] 프로필 및 워크스페이스 설정 기능 추가 및 수정
  src/api/sns-event-assistant/api-end-point.constants.ts
  src/api/sns-event-assistant/api.types.ts
  src/api/sns-event-assistant/get/apis/get-instagram.ts
  src/api/sns-event-assistant/get/queries/useInstagram.ts
  src/api/user/api.types.ts
  src/api/user/end-point.constants.ts
  src/api/user/get/apis/fetchUserDetail.ts
  src/api/user/get/apis/get-user-list-from-email.ts
  src/api/user/get/queries/useGetUserListFromEmail.ts
  src/api/user/patch/apis/fetchUserEdit.ts
  src/api/user/patch/mutations/useEditUserDetail.ts
  src/api/user/post/apis/post-user-password-check.ts
  src/api/user/post/mutations/usePostUserPasswordCheck.ts
  src/api/workspace/patch/mutations/useEditWorkspaceDetail.ts
  src/app/workspace/[workspaceId]/@innerWorkspaceIdModal/(.)settings/instagram-callback/page.tsx
  src/common/components/etc/calendar/DocumentFile/DocumentFile.client.tsx
  src/common/components/inputs/input-invite-member/InputInviteMember/InputInviteMember.client.tsx
  src/common/components/inputs/input-invite-member/InputInviteMember/InputInviteMember.stories.tsx
  src/common/components/inputs/input-invite-member/emails/EmailTag/EmailTag.client.tsx
  src/common/components/inputs/input-invite-member/emails/EmailTag/EmailTag.types.ts
  src/common/components/modals/ChangePasswordModal/ChangePasswordModal.client.tsx
  src/common/components/modals/ProfileSelectModal/ProfileSelectModal.client.tsx
  src/common/components/modals/ProfileSelectModal/ProfileSelectModal.types.ts
  src/common/components/modals/ProfileSelectModal/ProfileSettingMenu/ProfileSettingMenu.client.tsx
  src/common/components/modals/ProfileSelectModal/ProfileSettingMenu/ProfileSettingMenu.types.ts
  src/common/components/modals/ProfileSelectModal/WorkspaceSettingsMenu/WorkspaceSettingsMenu.client.tsx
  src/common/components/select-box/SelectBoxProfile/FooterButtons/FooterButtons.client.tsx
  src/common/components/select-box/SelectBoxProfile/SelectBoxProfile.client.tsx
  src/common/constants/query-key.constants.ts
  src/common/constants/routes.constants.ts
  src/features/sns-event-assistant/components/InstagramCallBackClient/InstagramCallBackClient.client.tsx
Labels: :sparkles: Feature, :wrench: Fix

#371 [Fix] 인스타그램 Route 위치 수정
  src/common/constants/routes.constants.ts
Labels: :wrench: Fix

#375 [Fix] 프로필 인스타그램 연결 WorkspaceId Zustand persist 속성 적용
  src/common/stores/workspace-id-store.ts
  src/features/sns-event-assistant/components/InstagramCallBackClient/InstagramCallBackClient.client.tsx
Labels: :wrench: Fix

#380 [Refactor] Calendar workspaceId number -> string 으로 변경
  src/api/workspace/api-end-point.constants.ts
  src/api/workspace/api.types.ts
  src/api/workspace/get/queries/useFetchCalendar.ts
  src/app/workspace/[workspaceId]/(assistant)/calendar/page.tsx
  src/app/workspace/[workspaceId]/page.tsx
  src/common/components/etc/calendar/CalendarSection/CalendarSection.client.tsx
  src/common/components/etc/calendar/CalendarSection/CalendarSection.types.ts
  src/common/constants/query-key.constants.ts
Labels: :recycle: Refactor

#389 [Refactor] 인스타그램 API에 location query 추가
  src/api/on-boarding/apis.types.ts
  src/api/on-boarding/post/apis/link-instagram.ts
  src/common/types/instagram.enum.types.ts
  src/features/on-boarding/components/OnBoardingCallBackClient/OnBoardingCallBackClient.client.tsx
  src/features/sns-event-assistant/components/InstagramCallBackClient/InstagramCallBackClient.client.tsx
Labels: :recycle: Refactor

#390 [Fix] Chart Section - PIE 짤림, 색 10개이상 사용가능, Bar 항목 표시, 주관식 줄바뀜 해결,
  src/common/components/survey/BarChart/bar-chart-config.ts
  src/common/components/survey/PieChart/PieChart.client.tsx
  src/common/components/survey/PieChart/PieChart.stories.tsx
  src/common/components/survey/PieChart/PieChart.types.ts
  src/common/components/survey/PieChart/pie-chart-config.ts
  src/common/components/survey/SubjectiveAnswer/SubjectiveAnswser.server.tsx
  src/features/team-mood-tracker/components/mood-reports/answer-section/TeamMoodAnswerChartSection/TeamMoodAnswerChartSection.client.tsx
Labels: :sparkles: Feature, :wrench: Fix
