Repository HaRu-Developers/haru-web, pull requests merged in 2025-07, with the labels that each got.

#27 [Feat] SVG 제작
  .prettierignore
  .storybook/main.ts
  eslint.config.mjs
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/common/components/LogoTest.stories.tsx
  src/common/components/LogoTest.tsx
  src/common/svgs/component-set/AiManagerIcon.svg
  src/common/svgs/component-set/AiQuestionHoverIcon.svg
  src/common/svgs/component-set/AiQuestionIcon.svg
  src/common/svgs/component-set/ArrowLeftIcon.svg
  src/common/svgs/component-set/ArrowRightIcon.svg
  src/common/svgs/component-set/CheckboxCircleDisableIcon.svg
  src/common/svgs/component-set/CheckboxCircleEnableIcon.svg
  src/common/svgs/component-set/CheckboxSquareDisableIcon.svg
  src/common/svgs/component-set/CheckboxSquareEnableIcon.svg
  src/common/svgs/component-set/CopyIcon.svg
  src/common/svgs/component-set/CrossLineIcon.svg
  src/common/svgs/component-set/DownloadDocsIcon.svg
  src/common/svgs/component-set/DownloadPdfIcon.svg
  src/common/svgs/component-set/DownloadWordIcon.svg
  src/common/svgs/component-set/DownloadhangulIcon.svg
  src/common/svgs/component-set/EditIcon.svg
  src/common/svgs/component-set/EyeCloseIcon.svg
  src/common/svgs/component-set/EyeOpenIcon.svg
  src/common/svgs/component-set/GnbAiManagerIcon.svg
  src/common/svgs/component-set/GnbCalenderIcon.svg
  src/common/svgs/component-set/GnbHomeIcon.svg
  src/common/svgs/component-set/GnbLogoutIcon.svg
  src/common/svgs/component-set/GnbProfileIcon.svg
  src/common/svgs/component-set/GnbRecentFileIcon.svg
  src/common/svgs/component-set/GnbSettingIcon.svg
  src/common/svgs/component-set/GnbSnsAssistIcon.svg
  src/common/svgs/component-set/GnbTeamMoodIcon.svg
  src/common/svgs/component-set/LinkIcon.svg
  src/common/svgs/component-set/PlusIcon.svg
  src/common/svgs/component-set/RecordingEndIcon.svg
  src/common/svgs/component-set/RecordingPauseIcon.svg
  src/common/svgs/component-set/RecordingPlayIcon.svg
  src/common/svgs/component-set/RecordingStartIcon.svg
  src/common/svgs/component-set/SnsAssistIcon.svg
  src/common/svgs/component-set/TeamMoodIcon.svg
  src/common/svgs/component-set/User1Icon.svg
  src/common/svgs/component-set/User2Icon.svg
  src/common/svgs/component-set/User3Icon.svg
  src/common/svgs/component-set/User4Icon.svg
  src/common/svgs/component-set/User5Icon.svg
  src/common/svgs/component-set/User6Icon.svg
  src/common/svgs/component-set/User7Icon.svg
  src/common/svgs/individual/ArrowUnderIcon.svg
  src/common/svgs/individual/CalenderIcon.svg
  src/common/svgs/individual/CongratulationIcon.svg
  src/common/svgs/individual/DownloadIcon.svg
  src/common/svgs/individual/SearchIcon.svg
  src/common/svgs/individual/WarningIcon.svg
  src/common/svgs/logo/LogoMixed.svg
  src/common/svgs/logo/LogoSimbol.svg
  src/common/svgs/logo/LogoText.svg
  src/common/types/svg.d.ts
Labels: :sparkles: Feature, D-0

#55 [Refactor] lint, prettier 적용 파일 변경, @svgs 경로 설정
  .prettierignore
  eslint.config.mjs
  lefthook.yml
  next.config.ts
  package.json
  pnpm-lock.yaml
  prettier.config.cjs
  src/common/components/LogoTest.tsx
  tsconfig.json
Labels: :recycle: Refactor, D-0

#57 [Chore] 디자인 시스템 수정사항 반영
  src/app/[test]/page.tsx
  src/styles/token/colors.css
  src/styles/token/fonts.css
Labels: :broom: Chore, D-0

#59 [Fix/Bug] 빌드 오류 수정
  .github/workflows/deploy.yml
Labels: :bug: Bug, D-0

#74 [Chore] gitmoji 추가 및 수정
  commitlint.config.cjs
Labels: :broom: Chore, D-0

#129 [Feat] TimePicker 컴포넌트 구현
  pnpm-lock.yaml
  src/app/layout.tsx
  src/common/components/TimePicker/TimePicker.client.tsx
  src/common/components/TimePicker/TimePicker.stories.tsx
  src/common/components/TimePicker/TimePicker.types.ts
  src/styles/globals.css
  src/styles/token/colors.css
  src/styles/token/scrollbar.css
  src/styles/token/shadows.css
  src/utils/timePickerUtils.ts
Labels: :sparkles: Feature, D-0

#31 [Feat] DatePicker 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/common/components/DatePicker/Body/DatePickerBody.client.tsx
  src/common/components/DatePicker/Body/DatePickerBody.stories.tsx
  src/common/components/DatePicker/Body/DatePickerBody.types.ts
  src/common/components/DatePicker/DateNum/DateNum.client.tsx
  src/common/components/DatePicker/DateNum/DateNum.stories.tsx
  src/common/components/DatePicker/DateNum/DateNum.types.ts
  src/common/components/DatePicker/DateNum/date-num-styles.ts
  src/common/components/DatePicker/DatePicker.client.tsx
  src/common/components/DatePicker/DatePicker.stories.tsx
  src/common/components/DatePicker/DatePicker.types.ts
  src/common/components/DatePicker/DatePickerFooter/DatePickerFooter.client.tsx
  src/common/components/DatePicker/DatePickerFooter/DatePickerFooter.stories.tsx
  src/common/components/DatePicker/DatePickerFooter/DatePickerFooter.types.ts
  src/common/components/DatePicker/DatePickerHeader/DatePickerHeader.client.tsx
  src/common/components/DatePicker/DatePickerHeader/DatePickerHeader.stories.tsx
  src/common/components/DatePicker/DatePickerHeader/DatePickerHeader.types.ts
  src/common/components/buttons/30px/DownloadButton.tsx
  src/common/components/buttons/30px/EditCompleteButton.tsx
  src/common/components/buttons/30px/NextStepButton.tsx
  src/common/components/buttons/30px/WriteCompleteButton.tsx
  src/common/components/buttons/30px/storybook/NextStepButton.stories.tsx
  src/common/components/buttons/32px/CompleteSelectButton/CompleteSelectButton.client.tsx
  src/common/components/buttons/38px/Cancel38pxButton.tsx
  src/common/components/buttons/38px/ConfirmEndingRecord.tsx
  src/common/components/buttons/38px/DeleteButton.tsx
  src/common/components/buttons/48px/LoginButton.tsx
  src/common/components/buttons/48px/NavigateToMainButton.tsx
  src/common/components/buttons/48px/RegisterButton.tsx
  src/common/components/buttons/56px/AddQuestionButton.tsx
  src/common/types/button.enum.ts
  src/styles/calendar-custom.css
Labels: :sparkles: Feature, D-0

#40 [Feat] 인풋 검색 박스 제작
  src/common/components/inputs/InputSearchBox.client.tsx
  src/common/components/inputs/InputSearchBox.stories.tsx
  src/common/components/inputs/InputSearchBox.types.ts
Labels: :sparkles: Feature, D-0

#50 [Feat] Pie & Bar & Subjective Component 구현
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/common/components/DatePicker/Body/DatePickerBody.client.tsx
  src/common/components/Survey/BarChart/BarChar.client.tsx
  src/common/components/Survey/BarChart/BarChart.stories.tsx
  src/common/components/Survey/BarChart/BarChart.types.ts
  src/common/components/Survey/BarChart/bar-chart-config.ts
  src/common/components/Survey/BarChart/bar-chart-plugin.ts
  src/common/components/Survey/ChartContainer/ChartContainer.server.tsx
  src/common/components/Survey/ChartContainer/ChartContainer.types.tsx
  src/common/components/Survey/PieChart/PieChar.client.tsx
  src/common/components/Survey/PieChart/PieChart.stories.tsx
  src/common/components/Survey/PieChart/PieChart.types.ts
  src/common/components/Survey/PieChart/pie-chart-config.ts
  src/common/components/Survey/PieChart/pie-chart-plugin.ts
  src/common/components/Survey/SubjectiveAnswer/SubjectiveAnswer.stories.tsx
  src/common/components/Survey/SubjectiveAnswer/SubjectiveAnswer.types.ts
  src/common/components/Survey/SubjectiveAnswer/SubjectiveAnswser.server.tsx
  src/common/components/buttons/30px/storybook/NextStepButton.stories.tsx
  src/styles/globals.css
  src/styles/token/fonts.css
Labels: :sparkles: Feature, D-0

#52 [Feat] 박스형 파일 컴포넌트 제작
  src/common/components/Etc/BoxedFile.client.tsx
  src/common/components/Etc/BoxedFile.stories.tsx
  src/common/components/Etc/BoxedFile.types.ts
  src/styles/token/fonts.css
Labels: :sparkles: Feature, D-0

#76 [Refactor] @utility -> @layer utilities 로 변경하기
  pnpm-lock.yaml
  src/app/test/joy/page.tsx
  src/styles/animation.css
  src/styles/token/colors.css
  src/styles/token/fonts.css
Labels: :recycle: Refactor, D-0

#53 [Feat] List File Component 구현
  src/app/test/jett/page.tsx
  src/common/components/ListFile/BaseListFile/BaseListFile.client.tsx
  src/common/components/ListFile/BaseListFile/BaseListFile.types.ts
  src/common/components/ListFile/HumanIconWithText/HumanIconWithText.server.tsx
  src/common/components/ListFile/HumanIconWithText/HumanIconWithText.types.ts
  src/common/components/ListFile/ListFileAiMeetingManager/ListFileAiMeetingManager.client.tsx
  src/common/components/ListFile/ListFileAiMeetingManager/ListFileAiMeetingManager.stories.tsx
  src/common/components/ListFile/ListFileAiMeetingManager/ListFileAiMeetingManager.types.ts
  src/common/components/ListFile/ListFileSnsEventAssistant/ListFileSnsEventAssistant.client.tsx
  src/common/components/ListFile/ListFileSnsEventAssistant/ListFileSnsEventAssistant.types.ts
  src/common/components/ListFile/ListFileSnsEventAssistant/ListFileSnsEventAssistent.stories.tsx
  src/common/components/ListFile/ListFileSnsEventAssistantLink/ListFileSnsEventAssistantLink.client.tsx
  src/common/components/ListFile/ListFileSnsEventAssistantLink/ListFileSnsEventAssistantLink.types.ts
  src/common/components/ListFile/ListFileSnsEventAssistantLink/ListFileSnsEventAssistentLink.stories.tsx
  src/common/components/ListFile/ListFileTeamMoodTracker/ListFileTeamMoodTracker.client.tsx
  src/common/components/ListFile/ListFileTeamMoodTracker/ListFileTeamMoodTracker.stories.tsx
  src/common/components/ListFile/ListFileTeamMoodTracker/ListFileTeamMoodTracker.types.ts
  src/common/components/icons/CheckboxIcons/CheckboxIcons.tsx
  src/common/components/icons/CheckboxIcons/CheckboxIcons.types.ts
Labels: :sparkles: Feature, D-0

#65 [Feat] 박스형 텍스트 Component 구현
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/app/test/kyeoungwoon/test/page.tsx
  src/common/components/BoxText/SnsLink/SnsLink.client.tsx
  src/common/components/BoxText/SnsLink/SnsLink.stories.tsx
  src/common/components/BoxText/SnsLink/SnsLink.types.ts
  src/common/components/BoxText/SurveyInSite/SurveyInSite.server.tsx
  src/common/components/BoxText/SurveyInSite/SurveyInSite.stories.tsx
  src/common/components/BoxText/SurveyInSite/SurveyInSite.types.ts
  src/common/components/BoxText/SurveyInfo/SurveyInfo.server.tsx
  src/common/components/BoxText/SurveyInfo/SurveyInfo.stories.tsx
  src/common/components/BoxText/SurveyInfo/SurveyInfo.types.ts
Labels: :sparkles: Feature, D-0

#79 [Feat] TAB 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  src/app/test/joy/page.tsx
  src/common/components/CategoryOption/CategoryOption.client.tsx
  src/common/components/CategoryOption/CategoryOption.stories.tsx
  src/common/components/CategoryOption/CategoryOption.types.ts
  src/common/components/buttons/30px/EditCompleteButton/EditCompleteButton.client.tsx
  src/common/components/buttons/IconButton/IconButton.client.tsx
  src/common/components/buttons/IconButton/IconButton.stories.tsx
  src/common/components/buttons/IconButton/IconButton.types.ts
  src/common/types/routing.types.ts
  src/features/ai-meeting-manager/components/panels/LeftPanel/LeftPanel.server.tsx
  src/features/ai-meeting-manager/components/panels/LeftPanel/LeftPanel.types.ts
  src/features/ai-meeting-manager/components/panels/LeftPanel/components/MeetingSummary/MeetingSummary.client.tsx
  src/features/ai-meeting-manager/components/panels/LeftPanel/components/MeetingVoiceLog/MeetingVoiceLog.server.tsx
  src/features/ai-meeting-manager/components/panels/RightPanel/RightPanel.client.tsx
  src/features/ai-meeting-manager/components/tabs/LeftTab/LeftTab.client.tsx
  src/features/ai-meeting-manager/components/tabs/LeftTab/LeftTab.stories.tsx
  src/features/ai-meeting-manager/components/tabs/LeftTab/LeftTab.types.ts
  src/features/ai-meeting-manager/components/tabs/RightTab/RightTab.client.tsx
  src/features/ai-meeting-manager/components/tabs/RightTab/RightTab.stories.tsx
  src/features/ai-meeting-manager/constants/tabs.ts
  src/features/ai-meeting-manager/hooks/stores/useTabStore.ts
  src/features/ai-meeting-manager/stores/tabStore.ts
  src/features/sns-event-assistant/components/Panel/Panel.server.tsx
  src/features/sns-event-assistant/components/Panel/Panel.types.ts
  src/features/sns-event-assistant/components/Panel/components/ParticipantList/ParticipantList.server.tsx
  src/features/sns-event-assistant/components/Panel/components/SnsLink/SnsLink.server.tsx
  src/features/sns-event-assistant/components/Panel/components/WinnerList/WinnerList.server.tsx
  src/features/sns-event-assistant/components/Tab/Tab.client.tsx
  src/features/sns-event-assistant/components/Tab/Tab.stories.tsx
  src/features/sns-event-assistant/components/Tab/Tab.types.ts
  src/features/sns-event-assistant/constants/tabs.ts
  src/features/team-mood-tracker/componets/panels/SurveyQuestionPanel/SurveyQuestionPanel.server.tsx
  src/features/team-mood-tracker/componets/panels/SurveyQuestionPanel/SurveyQuestionPanel.types.ts
  src/features/team-mood-tracker/componets/panels/TeamMoodReportPanel/TeamMoodReportPanel.server.tsx
  src/features/team-mood-tracker/componets/panels/TeamMoodReportPanel/TeamMoodReportPanel.types.ts
  src/features/team-mood-tracker/componets/panels/TeamMoodReportPanel/components/AnswerSummary/AnswerSummary.server.tsx
  src/features/team-mood-tracker/componets/panels/TeamMoodReportPanel/components/SurveyList/SurveyList.server.tsx
  src/features/team-mood-tracker/componets/panels/TeamMoodReportPanel/components/TeamMoodReport/TeamMoodReport.server.tsx
  src/features/team-mood-tracker/componets/tabs/SurveyQuestionTab/RightTab.stories.tsx
  src/features/team-mood-tracker/componets/tabs/SurveyQuestionTab/SurveyQuestionTab.client.tsx
  src/features/team-mood-tracker/componets/tabs/SurveyQuestionTab/SurveyQuestionTab.types.ts
  src/features/team-mood-tracker/componets/tabs/TeamMoodReportTab/TeamMoodReportTab.client.tsx
  src/features/team-mood-tracker/componets/tabs/TeamMoodReportTab/TeamMoodReportTab.stories.tsx
  src/features/team-mood-tracker/componets/tabs/TeamMoodReportTab/TeamMoodReportTab.types.ts
  src/features/team-mood-tracker/constants/tabs.ts
  src/features/team-mood-tracker/types/survey.types.ts
Labels: :sparkles: Feature, D-0

#128 [Refactor] 셀렉트 박스_프로필 pxr, 폰트 시스템 적용
  pnpm-lock.yaml
  src/common/components/select-box/select-box-profile/FooterButtons/FooterButtons.client.tsx
  src/common/components/select-box/select-box-profile/SelectBoxProfile/SelectBoxProfile.server.tsx
  src/common/components/select-box/select-box-profile/WorkSpaceItem/WorkSpaceItem.server.tsx
  src/features/team-mood-tracker/componets/tabs/SurveyQuestionTab/SurveyQuestionTab.client.tsx
  src/styles/token/shadows.css
Labels: :recycle: Refactor, D-0

#101 [Feat] 캘린터 컴포넌트 제작
  pnpm-lock.yaml
  scripts/generate-tailwind-pxr.cjs
  src/common/components/Etc/Calender.stories.tsx
  src/common/components/Etc/Calender.tsx
  src/common/components/Etc/Calender.types.ts
  src/features/team-mood-tracker/componets/tabs/SurveyQuestionTab/SurveyQuestionTab.client.tsx
  src/styles/token/define-pxr.css
Labels: :sparkles: Feature, D-0

#143 [Refactor] CI/CD flow 및 broken lock file 수정
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  .github/workflows/storybook.yml
  build.sh
  pnpm-lock.yaml
  scripts/build.sh
Labels: :bug: Bug, D-0

#137 [Bug] .next 파일에서 type-check error 발생
  tsconfig.json
Labels: :bug: Bug, D-0

#142 [Refactor] RootLayout에 clsx 적용
  src/app/layout.tsx
  src/common/components/gnbs/GnbLeft/RecentWorkspace/RecentWorkspace.server.tsx
  src/common/constants/gnbs.ts
  src/common/constants/routes.ts
Labels: :recycle: Refactor, D-0

#152 [Bug] lefthook의 validation script들에 명시적으로 exit 1 추가
  lefthook.yml
Labels: :bug: Bug, D-0

#158 [Feat] Toast 알림용 hook 생성
  prettier.config.cjs
  src/app/(main)/page.tsx
  src/app/layout.tsx
  src/app/test/joy/toast/page.tsx
  src/common/components/modals/SurveyLinkCreatedModal/DisplaySurveyLinkWithCopyButton/DisplaySurveyLinkWithCopyButton.server.tsx
  src/common/components/toast/Toast/Toast.client.tsx
  src/common/components/toast/Toast/Toast.types.tsx
  src/common/components/toast/Toaster/Toaster.client.tsx
  src/common/components/toast/types/toast.types.ts
  src/common/constants/toast.ts
  src/common/hooks/stores/useToastStore.ts
  src/common/stores/toastStore.ts
  src/common/types/toast.types.ts
  src/features/ai-meeting-manager/stores/tabStore.ts
  src/features/team-mood-tracker/componets/tabs/SurveyQuestionTab/SurveyQuestionTab.client.tsx
  tsconfig.json
Labels: :sparkles: Feature, D-1

#173 [Chore] 폰트 시스템 수정
  pnpm-lock.yaml
  src/styles/token/fonts.css
Labels: :broom: Chore, D-0

#175 [Refactor] time-picker-utils 종속
  eslint.config.mjs
  src/common/components/TimePicker/TimePicker.client.tsx
  src/common/components/TimePicker/utils/time-picker.utils.ts
Labels: :recycle: Refactor, D-0
